version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: alpine:3.7
    steps:
      - run: npm install
      - run: npm test