version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - run: npm install
      - run: npm run build
  test:
    docker:
      - image: circleci/node:12.16.0
    steps:
      - run: npm install
      - run: npm test